[package]
name = "battery"
version = "0.1.0"
edition = "2021"

[features]
default = [ "std" ]
std = []

[build-dependencies]
anyhow = "1.0"
dbc-codegen = { git = "https://github.com/technocreatives/dbc-codegen.git" }

[dependencies]
